name: go CI demo
on:
  push:
    branches:
      - master
      - kan
      - main
  pull_request:
    branches:
      - master

jobs:
  common:
    name: setup and checkout
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v1

  lint:
    name: Lint
    runs-on: self-hosted
    needs: common
    steps:
      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint Go Code
        run: |
          cd src
          cd server
          golangci-lint run

  build:
    name: build
    runs-on: self-hosted
    needs: common
    steps:
      - name: build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          cd src
          cd server
          go build .

  test:
    name: unit test
    runs-on: self-hosted
    needs: common
    steps:
      - name: test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          cd src
          cd server
          go test -v ./rest
